export default {
	"优惠券": [{
			"points_price": 800,
			"exchange_desc": "<p>兑换规则：会员可凭800积分兑换“5元代金券”1件。<p><p>售后服务：虚拟券不支持退换货服务，请先确认后兑换。<p>",
			"auto_off_datetime": null,
			"exchange_num_desc": "不限制",
			"goods_id": "28910",
			"exchange_limit": 0,
			"send_num": 0,
			"deleted_at": null,
			"multi_store_id": "0",
			"is_open_sale_time": 0,
			"created_at": "2022-03-20 14:16:25",
			"goods_name": "5元代金券",
			"total_num": 0,
			"sale_time_end": null,
			"goods_img": "[]",
			"multi_range_type": 0,
			"id": 574,
			"has_send_num": 0,
			"exchanged_num": 1241,
			"level_name": "",
			"is_vip_level": 0,
			"exchange_type": 1,
			"exchange_num": 0,
			"goods_cate_id": 2,
			"sort": 6,
			"level_ask": 0,
			"goods_type": 1,
			"coupon_data": null,
			"third_party_id": 0,
			"img": [],
			"third_party_name": "",
			"sale_time_start": null,
			"amount": "0.00",
			"goods_stock": 99665,
			"status": 1,
			"updated_at": "2023-05-11 09:37:06",
			"store_id": 23107,
			"level_id": 0,
			"auto_off_date": null
		},
		{
			"points_price": 500,
			"exchange_desc": "<p>兑换规则：会员可凭500积分兑换“任意水果茶兑换券”1件。<p><p>售后服务：虚拟券不支持退换货服务，请先确认后兑换。<p>",
			"auto_off_datetime": null,
			"exchange_num_desc": "不限制",
			"goods_id": "28321",
			"exchange_limit": 0,
			"send_num": 0,
			"deleted_at": null,
			"multi_store_id": "5809,7559",
			"is_open_sale_time": 0,
			"created_at": "2022-11-15 17:17:43",
			"goods_name": "水果茶兑换券",
			"total_num": 0,
			"sale_time_end": null,
			"goods_img": "[]",
			"multi_range_type": 2,
			"id": 380,
			"has_send_num": 0,
			"exchanged_num": 14201,
			"level_name": "",
			"is_vip_level": 0,
			"exchange_type": 1,
			"exchange_num": 0,
			"goods_cate_id": 2,
			"sort": 7,
			"level_ask": 0,
			"goods_type": 1,
			"coupon_data": null,
			"third_party_id": 0,
			"img": [],
			"third_party_name": "",
			"sale_time_start": null,
			"amount": "0.00",
			"goods_stock": 97377,
			"status": 1,
			"updated_at": "2023-05-11 10:47:28",
			"store_id": 23107,
			"level_id": 0,
			"auto_off_date": null
		},
		{
			"points_price": 1000,
			"exchange_desc": "<p>兑换规则：会员可凭1000积分兑换“10元代金券”1件。<p><p>售后服务：虚拟券不支持退换货服务，请先确认后兑换。<p>",
			"auto_off_datetime": null,
			"exchange_num_desc": "不限制",
			"goods_id": "28911",
			"exchange_limit": 0,
			"send_num": 0,
			"deleted_at": null,
			"multi_store_id": "5809,7559",
			"is_open_sale_time": 0,
			"created_at": "2022-12-21 11:27:56",
			"goods_name": "10元代金券",
			"total_num": 0,
			"sale_time_end": null,
			"goods_img": "[]",
			"multi_range_type": 2,
			"id": 433,
			"has_send_num": 0,
			"exchanged_num": 3940,
			"level_name": "",
			"is_vip_level": 0,
			"exchange_type": 1,
			"exchange_num": 0,
			"goods_cate_id": 2,
			"sort": 8,
			"level_ask": 0,
			"goods_type": 1,
			"coupon_data": null,
			"third_party_id": 0,
			"img": [],
			"third_party_name": "",
			"sale_time_start": null,
			"amount": "0.00",
			"goods_stock": 99111,
			"status": 1,
			"updated_at": "2023-05-11 10:43:23",
			"store_id": 23107,
			"level_id": 0,
			"auto_off_date": null
		}
	]
}
